name: macOS

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macos-11
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install dependencies
        run: |
          brew update
          brew install ninja

      - name: CMake configure -- Release
        run: cmake -S . -G "Ninja" -B cmake-build-release -DCMAKE_BUILD_TYPE=Release

      - name: CMake build -- Release
        run: cmake --build cmake-build-release

      - name: CTest -- Release
        run: ctest --test-dir cmake-build-release -C Release
